In [1]:
import pandas as pd

In [2]:
d=pd.read_csv(r"C:\Users\sivas\Downloads\loan_dataset.csv")
d

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,47,male,Associate,281514,29,RENT,17000,HOMEIMPROVEMENT,17.43,0.060,24,458,Yes,1
1,45,female,Associate,23583,23,MORTGAGE,16100,EDUCATION,11.13,0.683,9,537,No,1
2,21,male,Master,151505,2,MORTGAGE,17800,HOMEIMPROVEMENT,19.49,0.117,1,837,Yes,1
3,44,male,Associate,42036,22,RENT,30300,HOMEIMPROVEMENT,5.94,0.721,19,405,No,1
4,22,male,High School,46991,0,RENT,16700,EDUCATION,7.87,0.355,4,696,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,41,male,Master,54147,21,MORTGAGE,5400,EDUCATION,20.19,0.100,6,572,No,1
496,23,male,Associate,23308,2,RENT,20200,HOMEIMPROVEMENT,10.85,0.867,5,657,Yes,1
497,24,female,Bachelor,24361,2,RENT,16000,DEBTCONSOLIDATION,17.37,0.657,6,685,Yes,1
498,56,male,Master,104660,34,MORTGAGE,28100,VENTURE,22.31,0.268,25,711,No,0
499,60,female,Bachelor,96333,41,MORTGAGE,25600,PERSONAL,18.14,0.266,5,489,No,1

In [3]:
d.columns[d.isnull().any()]

Index([], dtype='object')

In [4]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      500 non-null    int64
 1   person_gender                   500 non-null    object
 2   person_education                500 non-null    object
 3   person_income                   500 non-null    int64
 4   person_emp_exp                  500 non-null    int64
 5   person_home_ownership           500 non-null    object
 6   loan_amnt                       500 non-null    int64
 7   loan_intent                     500 non-null    object
 8   loan_int_rate                   500 non-null    float64
 9   loan_percent_income             500 non-null    float64
 10  cb_person_cred_hist_length      500 non-null    int64
 11  credit_score                    500 non-null    int64
 12  previous_loan_defaults_on_file  500 non-null    object
 13  loan_status                     500 non-null    int64
dtypes: float64(2), int64(7), object(5)
memory usage: 54.8+ KB

In [5]:
fd=d.select_dtypes(include=["int64","float64"])
fd

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
0,47,281514,29,17000,17.43,0.060,24,458,1
1,45,23583,23,16100,11.13,0.683,9,537,1
2,21,151505,2,17800,19.49,0.117,1,837,1
3,44,42036,22,30300,5.94,0.721,19,405,1
4,22,46991,0,16700,7.87,0.355,4,696,1
...,...,...,...,...,...,...,...,...,...
495,41,54147,21,5400,20.19,0.100,6,572,1
496,23,23308,2,20200,10.85,0.867,5,657,1
497,24,24361,2,16000,17.37,0.657,6,685,1
498,56,104660,34,28100,22.31,0.268,25,711,0
499,60,96333,41,25600,18.14,0.266,5,489,1

In [7]:
fd.corr()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
person_age,1.000000,0.017407,0.994330,-0.056747,0.031659,-0.041124,0.476505,0.006009,-0.049731
person_income,0.017407,1.000000,0.022163,-0.026243,0.016965,-0.532424,-0.033553,0.008495,-0.175993
person_emp_exp,0.994330,0.022163,1.000000,-0.053915,0.028935,-0.039954,0.466705,0.004801,-0.045003
loan_amnt,-0.056747,-0.026243,-0.053915,1.000000,0.026379,0.676945,-0.090836,-0.016456,0.355817
loan_int_rate,0.031659,0.016965,0.028935,0.026379,1.000000,0.049968,-0.037090,-0.028772,0.381788
loan_percent_income,-0.041124,-0.532424,-0.039954,0.676945,0.049968,1.000000,-0.035579,-0.030990,0.353139
cb_person_cred_hist_length,0.476505,-0.033553,0.466705,-0.090836,-0.037090,-0.035579,1.000000,0.076567,-0.045737
credit_score,0.006009,0.008495,0.004801,-0.016456,-0.028772,-0.030990,0.076567,1.000000,-0.333947
loan_status,-0.049731,-0.175993,-0.045003,0.355817,0.381788,0.353139,-0.045737,-0.333947,1.000000

In [8]:
x=fd[["person_income"]]
y=fd["loan_status"]
x

     person_income
0           281514
1            23583
2           151505
3            42036
4            46991
..             ...
495          54147
496          23308
497          24361
498         104660
499          96333

[500 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_test

     person_income
361          50108
73           38091
374          48132
155          45069
104          72916
..             ...
347          43841
86           47844
75           52394
438          20283
15           37663

[100 rows x 1 columns]

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [13]:
y_pred=lr.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
accuracy_score(y_test,y_pred)

0.6